[pytest] 
log_cli = true
log_cli_level = DEBUG
log_cli_format = %(asctime)s %(levelname)s %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S

addopts = --html=report.html --self-contained-html -v
testpaths = tests/api_infinitychess

markers =
     smoke: Pruebas tipo smoke test
     negative: Pruebas con datos negativos
     functional: Pruebas funcionales
     regression: Pruebas de regresión
